### ISSUE TITLE
钱包模块：使用json钱包文件，查询地址余额报错

### ISSUE THREAD

**Issue by weimjsam** [aviland/platoncli-java#2]
环境 ：win10
jdk：Oracle jdk 8.0.2910.10

问题：【钱包模块】使用json钱包文件，查询地址余额报错

java -jar platoncli-java-jar-with-dependencies.jar account_getBalance -address 001.json
2021-07-07 11:34:38 INFO  钱包文件地址: atp1dj63qr9xdazjtswyxgek7yr2kwle6g63mk9f6y 匹配hrp: atp
2021-07-07 11:34:38 ERROR  Value must be in format 0x[1-9]+[0-9]* or 0x0
com.platon.exceptions.MessageDecodingException: Value must be in format 0x[1-9]+[0-9]* or 0x0
        at com.platon.utils.Numeric.decodeQuantity(Numeric.java:32)
        at com.platon.protocol.core.methods.response.PlatonGetBalance.getBalance(PlatonGetBalance.java:13)
        at com.cicdi.jcli.submodule.account.BalanceSubmodule.run(BalanceSubmodule.java:37)
        at com.cicdi.jcli.submodule.AbstractSimpleSubmodule.parse(AbstractSimpleSubmodule.java:118)
        at com.cicdi.jcli.Main.run(Main.java:86)
        at com.cicdi.jcli.submodule.AbstractSimpleSubmodule.parse(AbstractSimpleSubmodule.java:118)
        at com.cicdi.jcli.Main.main(Main.java:62)

**Comment by aviland** [comment]
通过增加json钱包作为参数的解析功能，已修复此bug

**Comment by weimjsam** [comment]
commit 8d92375e39e9102fc55925530621e34c94e9bccd

**Comment by weimjsam** [comment]
commit 8d92375e39e9102fc55925530621e34c94e9bccd
新版已修复
