### ISSUE TITLE
钱包模块：修改密码后选择备份，选择m参数后报错

### ISSUE THREAD

**Issue by weimjsam** [aviland/platoncli-java#3]
环境 ：win10
jdk：Oracle jdk 8.0.2910.10

问题：【钱包模块】修改密码后选择备份，选择m参数后报错

2021-07-06 11:13:28 INFO  已创建助记词密文文件:Bip39-new.001.json
2021-07-06 11:13:28 INFO  new.001.json: 已更新钱包文件，是否备份？Y/N
y
2021-07-06 11:13:32 INFO  备份助记词请输入m，备份私钥请输入p
m
2021-07-06 11:13:44 INFO  已找到助记词密文文件: Bip39-new.001.json
2021-07-06 11:13:44 ERROR  Given final block not properly padded. Such issues can arise if a bad key is used during decryption.
javax.crypto.BadPaddingException: Given final block not properly padded. Such issues can arise if a bad key is used during decryption.
        at com.sun.crypto.provider.CipherCore.unpad(CipherCore.java:975)
        at com.sun.crypto.provider.CipherCore.fillOutputBuffer(CipherCore.java:1056)
        at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:853)
        at com.sun.crypto.provider.AESCipher.engineDoFinal(AESCipher.java:446)
        at javax.crypto.Cipher.doFinal(Cipher.java:2168)
        at com.cicdi.jcli.util.AesUtil.decrypt(AesUtil.java:99)
        at com.cicdi.jcli.submodule.account.BackupsSubmodule.backupMnemonic(BackupsSubmodule.java:74)
        at com.cicdi.jcli.submodule.account.ModifySubmodule.run(ModifySubmodule.java:78)
        at com.cicdi.jcli.submodule.AbstractSimpleSubmodule.parse(AbstractSimpleSubmodule.java:118)
        at com.cicdi.jcli.Main.run(Main.java:86)
        at com.cicdi.jcli.submodule.AbstractSimpleSubmodule.parse(AbstractSimpleSubmodule.java:118)
        at com.cicdi.jcli.Main.main(Main.java:62)

**Comment by aviland** [comment]
原代码中使用新密码进行备份，现已换成使用原密码进行备份，此bug已修复

**Comment by weimjsam** [comment]
commit 8d92375e39e9102fc55925530621e34c94e9bccd
新版已修复
